name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - auritas
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - auritas

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Acceso dinámico a los secretos basado en el nombre de la rama
      - name: Inject environment variables dynamically
        env:
          REACT_APP_API_MAIN: ${{ secrets.REACT_APP_API_MAIN }}
          REACT_APP_API_AURITAS: ${{ secrets.REACT_APP_API_AURITAS }}
        run: |
          branch_name=$(echo "${GITHUB_REF_NAME}" | tr '[:lower:]' '[:upper:]') # Convierte a mayúsculas
          secret_var="REACT_APP_API_${branch_name}"
          api_url=${!secret_var} # Usa indirect expansion para obtener el valor del secreto
          if [ -z "$api_url" ]; then
            echo "ERROR: No se encontró un secreto para la rama $branch_name" >&2
            exit 1
          fi
          echo "REACT_APP_API_URL=$api_url" >> .env

      # Build and Deploy
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_COAST_0A5A43F0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_COAST_0A5A43F0F }}
          action: "close"
